# Generated by Django 3.2.23 on 2024-01-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_travelinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelinfo',
            name='bus_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
