# Generated by Django 3.2.23 on 2024-01-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_onboard',
            field=models.BooleanField(default=True),
        ),
    ]
