# Generated by Django 3.2.23 on 2024-01-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_onboard',
            field=models.BooleanField(default=False),
        ),
    ]
